# Generated by Django 2.2.3 on 2019-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('age', models.BigIntegerField()),
                ('sal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dep', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='authordetail',
            name='name',
        ),
    ]
