# Generated by Django 2.2.3 on 2019-08-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app001', '0003_auto_20190811_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
