# Generated by Django 2.2.3 on 2019-08-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app001', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
