# Generated by Django 2.2.3 on 2019-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app001', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='comment_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='read_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
