# Generated by Django 2.2.3 on 2019-08-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
