# Generated by Django 2.2.3 on 2019-08-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app01', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
